version: '3.1'

services:
  dw-br:
    image: postgres:15
    container_name: dw-br
    restart: unless-stopped
    environment:
     - POSTGRES_DB=dwbr
     - POSTGRES_USER=dwbr-user
     - POSTGRES_PASSWORD=Hc9iQoOs4xX7mxWeYYzzhA
    ports:
     - "5432:5432"
    volumes:
     - ./data/postgres:/var/lib/postgresql/data

