version: '3.1'

services:
  dw-bra:
    image: postgres:11
    container_name: dw-bra
    restart: unless-stopped
    environment:
     - POSTGRES_DB=dwbra
     - POSTGRES_USER=dwbra-user
     - POSTGRES_PASSWORD=Hc9iQoOs4xX7mxWeYYzzhA
    ports:
     - "5432:5432"
    volumes:
     - ./data/postgres:/var/lib/postgresql/data

