name: dwbra

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip
  - progress
  - psycopg2
  - requests
  - sqlalchemy
  - sqlalchemy_schemadisplay
  - unidecode
  - pip:
    - py7zr
    - uetl==0.0.8
