name: dwbr

channels:
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
    - dask
    - dask-sql
    - fastparquet
    - graphviz
    - numpy
    - openpyxl
    - pandas
    - prefect
    - prefect-dask
    - progress
    - py7zr
    - requests
    - sqlalchemy
    - sqlalchemy_schemadisplay
    - unidecode
    - uetl==0.1.5
