[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DW-BR"
authors = [{name = "Andre Pereira", email = "@ufpa.br"}]
dynamic = ["version", "description"]
