"""aux_create_tables.py
"""

AUX_DWUPDATE = """
CREATE TABLE aux_dwupdate
(
  DWUPDATE_SK SERIAL PRIMARY KEY
, UPDATE TIMESTAMP
, HOSTNAME VARCHAR(30)
, ELAPSED_TIME FLOAT8
);
"""

DIM_DATE = """
CREATE TABLE dim_date
(
  DATE_SK SERIAL PRIMARY KEY
, YEAR_NUMBER SMALLINT
, YEARMO_NUMBER INTEGER
, MONTH_NUMBER SMALLINT
, DAY_OF_YEAR_NUMBER SMALLINT
, DAY_OF_MONTH_NUMBER SMALLINT
, DAY_OF_WEEK_NUMBER SMALLINT
, WEEK_OF_YEAR_NUMBER SMALLINT
, DAY_NAME VARCHAR(30)
, MONTH_NAME VARCHAR(30)
, MONTH_SHORT_NAME VARCHAR(3)
, QUARTER_NUMBER SMALLINT
, WEEKEND_IND BOOLEAN
, DAYS_IN_MONTH SMALLINT
, DAY_DESC TEXT
, DAY_DATE TIMESTAMP
, WEEK_OF_MONTH_NUMBER SMALLINT
, YEAR_HALF_NUMBER SMALLINT
, LEAP_YEAR BOOLEAN
)
;CREATE INDEX idx_dim_date_lookup ON dim_date(DATE_SK)
;
"""

DIM_MUNICIPIO = """
CREATE TABLE dim_municipio
(
  MUNICIPIO_SK SERIAL PRIMARY KEY
, COD_SIAFI INT
, COD_IBGE INT
, CNPJ VARCHAR(14)
, UF VARCHAR(2)
, NOME VARCHAR(60)
);
"""

FATO_CAPES_AVALIACAO_PPG = """
CREATE TABLE fato_capes_avaliacao_ppg
(
  CAPES_SK SERIAL PRIMARY KEY
, MUNICIPIO_SK INTEGER REFERENCES DIM_MUNICIPIO(MUNICIPIO_SK)
, AN_BASE INT
, NM_GRANDE_AREA_CONHECIMENTO VARCHAR(100)
, SG_ENTIDADE_ENSINO VARCHAR(100)
, NM_ENTIDADE_ENSINO VARCHAR(100)
, NM_REGIAO VARCHAR(100)
, NM_MUNICIPIO_PROGRAMA_IES VARCHAR(100)
, SG_UF_PROGRAMA VARCHAR(10)
, CD_PROGRAMA_IES VARCHAR(200)
, NM_PROGRAMA_IES VARCHAR(200)
, CD_CONCEITO_PROGRAMA VARCHAR(5)
);
"""

FATO_RAIS = """
CREATE TABLE FATO_RAIS
(
 RAIS_SK BIGSERIAL PRIMARY KEY
, MUNICIPIO_SK INTEGER REFERENCES DIM_MUNICIPIO(MUNICIPIO_SK)
, MUNICIPIO_TRAB_SK INTEGER REFERENCES DIM_MUNICIPIO(MUNICIPIO_SK)
, BAIRROS_SP VARCHAR(20)
, BAIRROS_FORTALEZA VARCHAR(20)
, BAIRROS_RJ VARCHAR(20)
, CAUSA_AFASTAMENTO_1 INTEGER
, CAUSA_AFASTAMENTO_2 INTEGER
, CAUSA_AFASTAMENTO_3 INTEGER
, MOTIVO_DESLIGAMENTO INTEGER
, CBO_OCUPACAO_2002 VARCHAR(6)
, CNAE_2_CLASSE INTEGER
, CNAE_95_CLASSE INTEGER
, DISTRITOS_SP VARCHAR(20)
, VINCULO_ATIVO_31_12 BOOLEAN
, FAIXA_ETARIA INTEGER
, FAIXA_HORA_CONTRAT INTEGER
, FAIXA_REMUN_DEZEM_SM INTEGER
, FAIXA_REMUN_MEDIA_SM INTEGER
, FAIXA_TEMPO_EMPREGO INTEGER
, ESCOLARIDADE_APOS_2005 INTEGER
, QTD_HORA_CONTR INTEGER
, IDADE INTEGER
, IND_CEI_VINCULADO BOOLEAN
, IND_SIMPLES BOOLEAN
, MES_ADMISSAO INTEGER
, MES_DESLIGAMENTO INTEGER
, MUN_TRAB INTEGER
, MUNICIPIO INTEGER
, NACIONALIDADE INTEGER
, NATUREZA_JURIDICA INTEGER
, IND_PORTADOR_DEFIC BOOLEAN
, QTD_DIAS_AFASTAMENTO INTEGER
, RACA_COR INTEGER
, REGIOES_ADM_DF INTEGER
, VL_REMUN_DEZEMBRO_NOM FLOAT
, VL_REMUN_DEZEMBRO_SM FLOAT
, VL_REMUN_MEDIA_NOM FLOAT
, VL_REMUN_MEDIA_SM FLOAT
, CNAE_2_SUBCLASSE INTEGER
, SEXO_TRABALHADOR INTEGER
, TAMANHO_ESTABELECIMENTO INTEGER
, TEMPO_EMPREGO FLOAT
, TIPO_ADMISSAO INTEGER
, TIPO_ESTAB INTEGER
, TIPO_ESTAB_DESC VARCHAR(5)
, TIPO_DEFIC INTEGER
, TIPO_VINCULO INTEGER
, IBGE_SUBSETOR INTEGER
, VL_REM_JANEIRO_CC FLOAT
, VL_REM_FEVEREIRO_CC FLOAT
, VL_REM_MARCO_CC FLOAT
, VL_REM_ABRIL_CC FLOAT
, VL_REM_MAIO_CC FLOAT
, VL_REM_JUNHO_CC FLOAT
, VL_REM_JULHO_CC FLOAT
, VL_REM_AGOSTO_CC FLOAT
, VL_REM_SETEMBRO_CC FLOAT
, VL_REM_OUTUBRO_CC FLOAT
, VL_REM_NOVEMBRO_CC FLOAT
, ANO_CHEGADA_BRASIL INTEGER
, IND_TRAB_INTERMITENTE BOOLEAN
, IND_TRAB_PARCIAL BOOLEAN
, TIPO_SALARIO INTEGER
, VL_SALARIO_CONTRATUAL FLOAT
);
"""

# Data Warehouse Structure
DW_TABLES = dict(dim_date=DIM_DATE,
                 dim_municipio=DIM_MUNICIPIO,
                 fato_capes_avaliacao_ppg=FATO_CAPES_AVALIACAO_PPG,
                 fato_rais=FATO_RAIS,
                 aux_dwupdate=AUX_DWUPDATE,
                )
