"""aux_create_tables.py
"""

AUX_DWUPDATE = """
CREATE TABLE aux_dwupdate
(
  DWUPDATE_SK BIGSERIAL
, UPDATE TIMESTAMP
, HOSTNAME VARCHAR(30)
, ELAPSED_TIME FLOAT8
);
"""

DIM_DATE = """
CREATE TABLE dim_date
(
  DATE_SK BIGSERIAL
, YEAR_NUMBER SMALLINT
, YEARMO_NUMBER INTEGER
, MONTH_NUMBER SMALLINT
, DAY_OF_YEAR_NUMBER SMALLINT
, DAY_OF_MONTH_NUMBER SMALLINT
, DAY_OF_WEEK_NUMBER SMALLINT
, WEEK_OF_YEAR_NUMBER SMALLINT
, DAY_NAME VARCHAR(30)
, MONTH_NAME VARCHAR(30)
, MONTH_SHORT_NAME VARCHAR(3)
, QUARTER_NUMBER SMALLINT
, WEEKEND_IND BOOLEAN
, DAYS_IN_MONTH SMALLINT
, DAY_DESC TEXT
, DAY_DATE TIMESTAMP
, WEEK_OF_MONTH_NUMBER SMALLINT
, YEAR_HALF_NUMBER SMALLINT
, LEAP_YEAR BOOLEAN
)
;CREATE INDEX idx_dim_date_lookup ON dim_date(DATE_SK)
;
"""

DIM_MUNICIPIO = """
CREATE TABLE dim_municipio
(
  MUNICIPIO_SK BIGSERIAL
, COD_SIAFI INT
, COD_IBGE INT
, CNPJ VARCHAR(14)
, UF VARCHAR(2)
, NOME VARCHAR(60)
);
"""

FATO_CAPES_AVALIACAO_PPG = """
CREATE TABLE fato_capes_avaliacao_ppg
(
  CAPES_SK BIGSERIAL
, MUNICIPIO_SK BIGSERIAL
, AN_BASE INT
, NM_GRANDE_AREA_CONHECIMENTO VARCHAR(100)
, SG_ENTIDADE_ENSINO VARCHAR(100)
, NM_ENTIDADE_ENSINO VARCHAR(100)
, NM_REGIAO VARCHAR(100)
, NM_MUNICIPIO_PROGRAMA_IES VARCHAR(100)
, SG_UF_PROGRAMA VARCHAR(10)
, CD_PROGRAMA_IES VARCHAR(200)
, NM_PROGRAMA_IES VARCHAR(200)
, CD_CONCEITO_PROGRAMA VARCHAR(5)
);
"""

# Data Warehouse Structure
DW_TABLES = dict(dim_date=DIM_DATE,
                 dim_municipio=DIM_MUNICIPIO,
                 fato_capes_avaliacao_ppg=FATO_CAPES_AVALIACAO_PPG,
                 aux_dwupdate=AUX_DWUPDATE,
                )
